name: Check API Health

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:
  pull_request:
    branches:
      - main 

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run API Check
      run: python tests/check_api.py
